#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xineramaproto
Version  : 1.2.1
Release  : 5
URL      : http://xorg.freedesktop.org/releases/individual/proto/xineramaproto-1.2.1.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/xineramaproto-1.2.1.tar.bz2
Summary  : Xinerama extension headers
Group    : Development/Tools
License  : MIT

%description
X Xinerama Extension
This is an X extension that allows multiple physical screens controlled
by a single X server to appear as a single screen.

%package dev
Summary: dev components for the xineramaproto package.
Group: Development

%description dev
dev components for the xineramaproto package.


%prep
%setup -q -n xineramaproto-1.2.1

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/panoramiXproto.h
/usr/lib64/pkgconfig/*.pc
